#!/bin/bash -login 

#PBS -l walltime=96:00:00,nodes=1:ppn=9,mem=64gb
#PBS -N sp_cdx_tophat
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe                                                                                                                                                                                                     

module load bowtie2
module load TopHat/2.0.8b
module load HTSeq/0.6.1

WKDR=${SCRATCH}/urchin_cdx/tophat/
mkdir $WKDR
cd $WKDR
ln -fs ${SCRATCH}/urchin_cdx/*trim.fq .

sample[1]=SpCdx1_ATCACG_L002
sample[2]=SpCdx2_GATCAG_L002
sample[3]=SpCdx3_CCGTCC_L002
sample[4]=SpCdxContr1_TTAGGC_L002
sample[5]=SpCdxContr2_TAGCTT_L002
sample[6]=SpCdxContr3_GTCCGC_L002

reference='/mnt/home/loweelij/Napoli/Spur_v3.1_assembly/LinearScaffolds/Spur_3.1.LinearScaffold.fa'
reference_index=lox_bowtie2
gff=${HOME}/Napoli/SpBase3.1_build7.gff3/Transcriptome.gff3

bowtie2-build ${reference} ${reference_index}
for i in 1 2 3 4 5 6
do 
    tophat -p 8 -o ${sample[i]} ${reference_index} ${sample[i]}_R1_001.trim.fq ${sample[i]}_R2_001.trim.fq,${sample[i]}_SE_001.trim.fq
    samtools sort -n ${sample[i]}/accepted_hits.bam ${sample[i]}/accepted_hits.sorted
    samtools index ${sample[i]}/accepted_hits.sorted.bam
    htseq-count --format=bam -a5 --stranded=no --type=gene --order=name --idattr=ID ${sample[i]}/accepted_hits.sorted.bam $gff > ${sample[i]}_htseq_counts.txt
done

qstat -f ${PBS_JOBID}