#!/bin/bash -login

#PBS -l walltime=24:00:00,nodes=1:ppn=5,mem=16gb
#PBS -N trim_sp_lox
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load Trimmomatic/0.32

WKD=${SCRATCH}/urchin_lox/
#mkdir $WKD
cd $WKD
ln -fs ${HOME}/Napoli/hard_drive/dati_RNA_Seq/*/*gz .

for i in *R1_001.fastq.gz
do
    java -jar $TRIM/trimmomatic PE -threads 4 $i ${i/R1/R2} s1_pe s1_se s2_pe s2_se HEADCROP:14 ILLUMINACLIP:$TRIM/adapters/TruSeq3-PE.fa:2:40:15 LEADING:5 TRAILING:5 SLIDINGWINDOW:4:5 MINLEN:25
    mv s1_pe ${i/.fastq.gz/.trim.fq}
    mv s2_pe ${i/R1_001.fastq.gz/R2_001.trim.fq}
    cat s1_se s2_se > ${i/R1_001.fastq.gz/SE_001.trim.fq}
done

qsub ${HOME}/paraHox_analysis/scripts/sp_lox48.qsub
qsub ${HOME}/paraHox_analysis/scripts/sp_lox72.qsub

qstat -f ${PBS_JOBID}

